# mkdocs.yml
site_name: "Knickknacks"
site_author: "Nick Stockton"
site_description: "Knickknacks Main Page"
site_url: "https://nstockton.github.io/knickknacks"
repo_name: "nstockton/knickknacks"
repo_url: "https://github.com/nstockton/knickknacks"
edit_uri: "blob/master/docs/"
copyright: "Copyright \xa9 2024 Nick Stockton"
docs_dir: "docs"
site_dir: "site"

nav:
  - Home: index.md
  - API Index: api/index.md
  - API Navigation:
      - iterables.py: api/iterables.md
      - numbers.py: api/numbers.md
      - platforms.py: api/platforms.md
      - strings.py: api/strings.md
      - testing.py: api/testing.md
      - utils.py: api/utils.md
  - License: license.md

theme:
  name: "material"
  custom_dir: "material_theme/"
  include_search_page: false
  search_index_only: false
  highlightjs: true
  hljs_languages:
    - python
  hljs_style: github
  navigation_depth: 2
  #nav_style: "dark"
  shortcuts:
    help: 191    # ?
    next: 78     # n
    previous: 80 # p
    search: 83   # s

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - pymdownx.snippets:
      base_path: docs
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tabbed
  - toc:
      permalink: true

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.insert(0, "docs")
          rendering:
            show_root_heading: true
            heading_level: 1
            group_by_category: true
            show_source: true
          selection:
            docstring_style: google
            inherited_members: true
            docstring_options:
              replace_admonitions: yes
            filters:
              - "!^_"  # Private items.
              - "^__init__$"  # Except for __init__.
      custom_templates: "mkdocstrings_templates"
      watch:
        - "src/knickknacks"
